@startuml cu01_login
title User Login with OTP

actor User
participant Gateway  
participant AuthService
participant MailSender
database AuthDB

User -> Gateway: POST /auth/login 
Gateway -> AuthService: loginwithMFA(email, password)
AuthService -> AuthDB: findByEmail(email)

alt Invalid credentials
    AuthDB --> AuthService: user not found
    AuthService --> Gateway: 401 Unauthorized
    Gateway --> User: Login failed: invalid credentials
else Valid credentials
    AuthDB --> AuthService: user found

    AuthService -> MailSender: sendOTP(otp, email)
    MailSender --> AuthService: OTP sent
    AuthService --> Gateway: MFA_REQUIRED
    Gateway --> User: MFA required 

    User -> Gateway: Enter OTP code
    Gateway -> AuthService: verifyOTP(email, code)
    AuthService -> AuthDB: check OTP 

    alt Invalid OTP
        AuthDB --> AuthService: invalid
        AuthService --> Gateway: 400 Bad Request
        Gateway --> User: Invalid OTP
    else Valid OTP
        AuthDB --> AuthService: valid
        AuthService --> Gateway: JWT token
        Gateway --> User: login success
    end
end

@enduml