@startuml dss_uc05
title DSS - UC05: Placement d'un ordre

actor ":Client" as Client
participant ":Système" as System

== Placement d'ordre d'achat ==
Client -> System : acheterAction(String symbol,  double price, int quantity)
alt Fonds suffisants et ordre valide
    System --> Client : message confirmation : "ordre placé avec succès", numéroOrdre, statutOrdre
else Fonds insuffisants ou ordre invalide
    System --> Client : message erreur : "solde insuffisant" ou "ordre invalide"
end

== Placement d'ordre de vente ==
Client -> System : vendreAction(String symbol,  double price, int quantity)
alt Actions disponibles et ordre valide
    System --> Client : message confirmation : "ordre placé avec succès", numéroOrdre, statutOrdre
else Actions insuffisantes ou ordre invalide
    System --> Client : message erreur : "actions insuffisantes" ou "ordre invalide"
end

@enduml